In [4]:
import pandas as pd

df = pd.read_csv("../data/raw/houses_hcm_10000_raw.csv")

print("Kích thước:", df.shape)
print("\nCác cột:")
print(df.columns.tolist())

Kích thước: (10000, 19)

Các cột:
['name', 'description', 'property_type_name', 'province_name', 'district_name', 'ward_name', 'street_name', 'project_name', 'price', 'area', 'floor_count', 'frontage_width', 'house_depth', 'road_width', 'bedroom_count', 'bathroom_count', 'house_direction', 'balcony_direction', 'published_at']

In [5]:
df.head()

,name,description,property_type_name,province_name,district_name,ward_name,street_name,project_name,price,area,floor_count,frontage_width,house_depth,road_width,bedroom_count,bathroom_count,house_direction,balcony_direction,published_at
0,"Bán căn hộ dịch vụ 40 phòng, lợi nhuận ổn định...",Bán căn hộ dịch vụ mặt tiền 164 - 166 Nguyễn C...,Nhà,Hồ Chí Minh,Tân Phú,Tân Sơn Nhì,Nguyễn Cửu Đàm,NaN,3.500000e+10,130.0,NaN,8.0,NaN,NaN,NaN,NaN,Đông Bắc,Đông Bắc,2025-06-26T11:24:18
1,"Nguyễn Ngọc Lộc Q10, 5tầng BTCT hẻm 5m thông, ...",NGUYỄN NGỌC LỘC - HẺM XE HƠI 5M THÔNG - NHÀ 5 ...,Nhà,Hồ Chí Minh,10,14,Nguyễn Ngọc Lộc,NaN,6.500000e+09,24.0,5.0,3.7,NaN,NaN,3.0,4.0,NaN,NaN,2025-11-17T15:36:52.649000
2,"Nhà hẻm xe hơi ngay Aeon Mall Tân Phú, diện tí...",Nhà siêu hot ngay Aeon Mall Tân Phú đây! Diện ...,Nhà,Hồ Chí Minh,11,NaN,NaN,NaN,6.000000e+09,124.0,NaN,4.0,31.0,NaN,3.0,NaN,NaN,NaN,2025-09-16T09:56:07.702000
3,"Bán chung cư 4PN, 4WC tại Tôn Thất Thuyết, 64m...","Căn hộ chung cư nằm tại Đường Tôn Thất Thuyết,...",Căn hộ chung cư,Hồ Chí Minh,4,1,Tôn Thất Thuyết,NaN,7.500000e+09,64.0,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,2026-03-20T21:24:50.219000
4,"Bán gấp CC Tây Thạnh DT 72m2, 2 tỷ 7 TL 2PN 2W...","Bán chung cư Tây Thạnh, P. Tây Thạnh, Q. Tân P...",Căn hộ chung cư,Hồ Chí Minh,Tân Phú,Tây Thạnh,C8,NaN,2.700000e+09,72.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,2025-10-17T09:40:43.092000

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                10000 non-null  str
 1   description         10000 non-null  str
 2   property_type_name  10000 non-null  str
 3   province_name       10000 non-null  str
 4   district_name       9364 non-null   str
 5   ward_name           8369 non-null   str
 6   street_name         6694 non-null   str
 7   project_name        2426 non-null   str
 8   price               10000 non-null  float64
 9   area                10000 non-null  float64
 10  floor_count         2995 non-null   float64
 11  frontage_width      4590 non-null   float64
 12  house_depth         68 non-null     float64
 13  road_width          1665 non-null   float64
 14  bedroom_count       7131 non-null   float64
 15  bathroom_count      6746 non-null   float64
 16  house_direction     1963 non-null   str
 17  balcony_direction   1323 non-null   str
 18  published_at        10000 non-null  str
dtypes: float64(8), str(11)
memory usage: 9.6 MB

In [7]:
df.isnull().sum()

name                     0
description              0
property_type_name       0
province_name            0
district_name          636
ward_name             1631
street_name           3306
project_name          7574
price                    0
area                     0
floor_count           7005
frontage_width        5410
house_depth           9932
road_width            8335
bedroom_count         2869
bathroom_count        3254
house_direction       8037
balcony_direction     8677
published_at             0
dtype: int64

In [8]:
print("Số dòng, số cột:", df.shape)

Số dòng, số cột: (10000, 19)

In [9]:
df.head(10)

,name,description,property_type_name,province_name,district_name,ward_name,street_name,project_name,price,area,floor_count,frontage_width,house_depth,road_width,bedroom_count,bathroom_count,house_direction,balcony_direction,published_at
0,"Bán căn hộ dịch vụ 40 phòng, lợi nhuận ổn định...",Bán căn hộ dịch vụ mặt tiền 164 - 166 Nguyễn C...,Nhà,Hồ Chí Minh,Tân Phú,Tân Sơn Nhì,Nguyễn Cửu Đàm,NaN,3.500000e+10,130.00,NaN,8.0,NaN,NaN,NaN,NaN,Đông Bắc,Đông Bắc,2025-06-26T11:24:18
1,"Nguyễn Ngọc Lộc Q10, 5tầng BTCT hẻm 5m thông, ...",NGUYỄN NGỌC LỘC - HẺM XE HƠI 5M THÔNG - NHÀ 5 ...,Nhà,Hồ Chí Minh,10,14,Nguyễn Ngọc Lộc,NaN,6.500000e+09,24.00,5.0,3.7,NaN,NaN,3.0,4.0,NaN,NaN,2025-11-17T15:36:52.649000
2,"Nhà hẻm xe hơi ngay Aeon Mall Tân Phú, diện tí...",Nhà siêu hot ngay Aeon Mall Tân Phú đây! Diện ...,Nhà,Hồ Chí Minh,11,NaN,NaN,NaN,6.000000e+09,124.00,NaN,4.0,31.0,NaN,3.0,NaN,NaN,NaN,2025-09-16T09:56:07.702000
3,"Bán chung cư 4PN, 4WC tại Tôn Thất Thuyết, 64m...","Căn hộ chung cư nằm tại Đường Tôn Thất Thuyết,...",Căn hộ chung cư,Hồ Chí Minh,4,1,Tôn Thất Thuyết,NaN,7.500000e+09,64.00,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,2026-03-20T21:24:50.219000
4,"Bán gấp CC Tây Thạnh DT 72m2, 2 tỷ 7 TL 2PN 2W...","Bán chung cư Tây Thạnh, P. Tây Thạnh, Q. Tân P...",Căn hộ chung cư,Hồ Chí Minh,Tân Phú,Tây Thạnh,C8,NaN,2.700000e+09,72.00,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,2025-10-17T09:40:43.092000
5,Full rổ hàng Dreamhome Riverside giá gốc CĐT c...,"Còn vài căn suất nội bộ. - 56,83m2: 1,3 tỷ. - ...",Căn hộ chung cư,Hồ Chí Minh,8,7,Nguyễn Văn Linh,Dream Home Riverside,1.490000e+09,62.37,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,2025-08-26T11:15:49.273000
6,Giảm 3tỷ khách sạn 5 tầng 32 phòng ngay Phạm V...,Bán khách sạn 5 tầng - đang kinh doanh ổn định...,Nhà,Hồ Chí Minh,Thủ Đức,Hiệp Bình Chánh,NaN,NaN,2.350000e+10,162.20,5.0,5.5,NaN,6.0,32.0,33.0,Đông - Nam,Đông - Nam,2025-09-28T08:48:55.035000
7,"Bán nhà mặt phố tại 435 Phạm Văn Đồng, 10,4 tỷ...","Nhà mặt phố tại 435 , Đường Phạm Văn Đồng, Phư...",Nhà,Hồ Chí Minh,Bình Thạnh,11,Phạm Văn Đồng,NaN,1.040000e+10,65.00,NaN,4.0,NaN,NaN,NaN,2.0,Nam,NaN,2026-02-20T03:45:10.834000
8,"Nhà hẻm xe hơi 10m thông Nguyễn Cửu Vân, P.25,...",Chủ nhà cấn bán gấp căn nhà hẻm xe hơi 10m đườ...,Nhà,Hồ Chí Minh,Bình Thạnh,25,NaN,NaN,1.850000e+10,95.00,NaN,4.5,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-24T22:04:12.341000
9,Em Đạt nắm nhiều căn New City 1PN giá từ 5 tỷ....,* New City Thủ Thiêm 1PN giá từ 5 tỷ. * Vị trí...,Căn hộ chung cư,Hồ Chí Minh,Thủ Đức,NaN,NaN,New City Thủ Thiêm,5.000000e+09,51.00,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2026-01-14T12:23:27.771000

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                10000 non-null  str
 1   description         10000 non-null  str
 2   property_type_name  10000 non-null  str
 3   province_name       10000 non-null  str
 4   district_name       9364 non-null   str
 5   ward_name           8369 non-null   str
 6   street_name         6694 non-null   str
 7   project_name        2426 non-null   str
 8   price               10000 non-null  float64
 9   area                10000 non-null  float64
 10  floor_count         2995 non-null   float64
 11  frontage_width      4590 non-null   float64
 12  house_depth         68 non-null     float64
 13  road_width          1665 non-null   float64
 14  bedroom_count       7131 non-null   float64
 15  bathroom_count      6746 non-null   float64
 16  house_direction     1963 non-null   str
 17  balcony_direction   1323 non-null   str
 18  published_at        10000 non-null  str
dtypes: float64(8), str(11)
memory usage: 9.6 MB

In [11]:
df.isnull().sum()

name                     0
description              0
property_type_name       0
province_name            0
district_name          636
ward_name             1631
street_name           3306
project_name          7574
price                    0
area                     0
floor_count           7005
frontage_width        5410
house_depth           9932
road_width            8335
bedroom_count         2869
bathroom_count        3254
house_direction       8037
balcony_direction     8677
published_at             0
dtype: int64

In [12]:
print("THỐNG KÊ GIÁ:")
print(df["price"].describe())
print("\nTHỐNG KÊ DIỆN TÍCH:")
print(df["area"].describe())

THỐNG KÊ GIÁ:
count    1.000000e+04
mean     1.853794e+10
std      1.070734e+11
min      4.850000e+08
25%      5.099750e+09
50%      7.723000e+09
75%      1.400000e+10
max      9.930300e+12
Name: price, dtype: float64

THỐNG KÊ DIỆN TÍCH:
count    10000.000000
mean       106.185230
std        167.170915
min          4.200000
25%         55.000000
50%         72.000000
75%        102.000000
max       7200.000000
Name: area, dtype: float64

In [13]:
print("=== KIỂM TRA GIÁ ===")

print("\nCác mức giá thấp nhất:")
print(df["price"].sort_values().head(20).to_string(index=False))

print("\nCác mức giá cao nhất:")
print(df["price"].sort_values(ascending=False).head(20).to_string(index=False))

print("\nCác phân vị của giá:")
print(df["price"].quantile([0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99, 0.995, 1.0]))

=== KIỂM TRA GIÁ ===

Các mức giá thấp nhất:
485000000.0
520000000.0
630000000.0
650000000.0
650000000.0
745000000.0
749000000.0
750000000.0
770000000.0
790000000.0
800000000.0
820000000.0
820000000.0
820000000.0
830000000.0
835000000.0
838000000.0
840000000.0
840000000.0
860000000.0

Các mức giá cao nhất:
9.930300e+12
1.250000e+12
1.250000e+12
8.500000e+11
7.500000e+11
7.000000e+11
7.000000e+11
6.500000e+11
5.600000e+11
5.000000e+11
4.500000e+11
4.500000e+11
4.060000e+11
4.000000e+11
3.990000e+11
3.820000e+11
3.800000e+11
3.700000e+11
3.700000e+11
3.700000e+11

Các phân vị của giá:
0.010    1.599700e+09
0.050    2.600000e+09
0.250    5.099750e+09
0.500    7.723000e+09
0.750    1.400000e+10
0.950    6.200000e+10
0.990    1.750100e+11
0.995    2.700000e+11
1.000    9.930300e+12
Name: price, dtype: float64

In [14]:
print("=== KIỂM TRA OUTLIER GIÁ ===")

for nguong in [20e9, 30e9, 50e9, 100e9, 200e9, 500e9, 1e12]:
    so_luong = (df["price"] > nguong).sum()
    print(f"Giá > {nguong/1e9:.0f} tỷ: {so_luong} tin")

=== KIỂM TRA OUTLIER GIÁ ===
Giá > 20 tỷ: 1761 tin
Giá > 30 tỷ: 1163 tin
Giá > 50 tỷ: 660 tin
Giá > 100 tỷ: 234 tin
Giá > 200 tỷ: 74 tin
Giá > 500 tỷ: 9 tin
Giá > 1000 tỷ: 3 tin

In [15]:
print("=== NHỮNG TIN CÓ GIÁ CAO NHẤT ===")

cols = [
    "price",
    "area",
    "district_name",
    "ward_name",
    "property_type_name",
    "description"
]

cols_co = [c for c in cols if c in df.columns]

df.sort_values("price", ascending=False)[cols_co].head(20)

=== NHỮNG TIN CÓ GIÁ CAO NHẤT ===

,price,area,district_name,ward_name,property_type_name,description
5309,9.930300e+12,419.0,Tân Phú,Sơn Kỳ,Căn hộ chung cư,"THÔNG TIN CĂN V3.06 - DT: 419m² (bao gồm hầm),..."
4497,1.250000e+12,1320.0,1,Bến Nghé,Nhà,Vị trí hiếm có độc quyền quận 1 mặt tiền hơn 1...
4704,1.250000e+12,1468.0,1,Bến Nghé,Nhà,"Bên trái Somerset, bên phải Tổng Lãnh Sự Quán ..."
2761,8.500000e+11,1060.0,Phú Nhuận,NaN,Nhà,"- Siêu vị trí có 1 không 2, khuôn đất cực kỳ h..."
7062,7.500000e+11,850.0,Phú Nhuận,NaN,Nhà,Bán gấp tòa nhà hàng B - Mặt tiền Nguyễn Văn T...
2660,7.000000e+11,1425.0,Bình Thạnh,NaN,Nhà,Biểu tượng quyền lực giữa lòng thành phố. Tòa ...
9716,7.000000e+11,669.5,1,Đa Kao,Nhà,"Chủ cần bán tòa nhà Hai Bà Trưng, Đa Kao Quận ..."
92,6.500000e+11,816.0,3,Võ Thị Sáu,Nhà,"BIỆT THỰ MT TRƯƠNG ĐỊNH, PHƯỜNG VÕ THỊ SÁU, QU..."
5662,5.600000e+11,816.0,3,Võ Thị Sáu,Nhà,Diện tích khủng: 820m2 (21x42) 2 mặt tiền cực ...
9404,5.000000e+11,437.5,1,Bến Nghé,Biệt thự/Nhà liền kề,"Chú tôi định cư Pháp, nên cần bán đi căn góc đ..."
1155,4.500000e+11,387.0,1,Nguyễn Cư Trinh,Nhà,Bán gấp xuất cảnh - Tòa nhà mặt tiền Nguyễn Tr...
3217,4.500000e+11,550.0,NaN,NaN,Biệt thự/Nhà liền kề,Bán biệt thự Sala căn giới hạn siêu hiếm 450 t...
735,4.060000e+11,677.0,3,Võ Thị Sáu,Nhà,"Siêu khan hiếm, khu vực rất ít nhà bán. Bán nh..."
6633,4.000000e+11,391.0,3,Võ Thị Sáu,Nhà,"Bán Khách sạn 77 phòng Mặt tiền Võ Văn Tần, P...."
4579,3.990000e+11,700.0,3,2,Nhà,"Bán nhà Quận 3 HCM, trục đường chính, cách ngã..."
518,3.820000e+11,677.0,3,Võ Thị Sáu,Nhà,Lý do bán: Chủ nhà cần tiền thanh khoản gấp để...
7347,3.800000e+11,700.0,1,Phạm Ngũ Lão,Nhà,"- Bán toà nhà góc 2 mặt tiền Nguyễn Trãi, P. P..."
4188,3.700000e+11,252.0,1,Bến Nghé,Nhà,"""Bán nhà 2MT Pasteur Bến Nghé Q.1 Vị Trí Kim C..."
6383,3.700000e+11,3000.0,Thủ Đức,Tăng Nhơn Phú A,Nhà,Chính chủ bán gấp quỹ đất mặt tiền Lê Văn Việt...
2674,3.700000e+11,6000.0,Phú Nhuận,9,Nhà,Thông tin chi tiết: Diện tích: 6.000m². Giá bá...

In [16]:
print("=== 9 TIN CÓ GIÁ TRÊN 500 TỶ ===")

df_cao = df[df["price"] > 500e9].copy()

cols = [
    "price",
    "area",
    "district_name",
    "ward_name",
    "property_type_name",
    "bedroom_count",
    "bathroom_count",
    "floor_count",
    "description"
]

cols_co = [c for c in cols if c in df.columns]

print("Số tin:", len(df_cao))
display(
    df_cao[cols_co]
    .sort_values("price", ascending=False)
)

=== 9 TIN CÓ GIÁ TRÊN 500 TỶ ===
Số tin: 9

,price,area,district_name,ward_name,property_type_name,bedroom_count,bathroom_count,floor_count,description
5309,9.930300e+12,419.0,Tân Phú,Sơn Kỳ,Căn hộ chung cư,5.0,NaN,NaN,"THÔNG TIN CĂN V3.06 - DT: 419m² (bao gồm hầm),..."
4497,1.250000e+12,1320.0,1,Bến Nghé,Nhà,NaN,NaN,NaN,Vị trí hiếm có độc quyền quận 1 mặt tiền hơn 1...
4704,1.250000e+12,1468.0,1,Bến Nghé,Nhà,NaN,NaN,NaN,"Bên trái Somerset, bên phải Tổng Lãnh Sự Quán ..."
2761,8.500000e+11,1060.0,Phú Nhuận,NaN,Nhà,NaN,NaN,NaN,"- Siêu vị trí có 1 không 2, khuôn đất cực kỳ h..."
7062,7.500000e+11,850.0,Phú Nhuận,NaN,Nhà,NaN,NaN,NaN,Bán gấp tòa nhà hàng B - Mặt tiền Nguyễn Văn T...
9716,7.000000e+11,669.5,1,Đa Kao,Nhà,NaN,NaN,NaN,"Chủ cần bán tòa nhà Hai Bà Trưng, Đa Kao Quận ..."
2660,7.000000e+11,1425.0,Bình Thạnh,NaN,Nhà,NaN,NaN,17.0,Biểu tượng quyền lực giữa lòng thành phố. Tòa ...
92,6.500000e+11,816.0,3,Võ Thị Sáu,Nhà,NaN,NaN,NaN,"BIỆT THỰ MT TRƯƠNG ĐỊNH, PHƯỜNG VÕ THỊ SÁU, QU..."
5662,5.600000e+11,816.0,3,Võ Thị Sáu,Nhà,NaN,NaN,NaN,Diện tích khủng: 820m2 (21x42) 2 mặt tiền cực ...